apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "identity-server.fullname" . }}
  labels:
    {{- include "identity-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - identity.kubeshield.io
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: ["list"]
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["create"]
